<application>
  <component name="RecentProjectsManager">
    <option name="recentPaths">
      <list>
        <option value="F:/across global/Android-Instagram-Clone-e005e9b029514ec6380d49703985e3f40bbf221e" />
        <option value="F:/across global/AcrossGlobal" />
        <option value="F:/across global/MVP-Example-master" />
        <option value="F:/Jntuk/JntukInterview-master" />
        <option value="F:/Jntuk/Form" />
        <option value="F:/Jntuk/Form1" />
        <option value="F:/Android Stuff/TextFieldMaterial" />
        <option value="F:/Jntuk/NewPipe-dev" />
        <option value="F:/Jntuk/Gogaga" />
        <option value="F:/opensoure/Timber-master" />
        <option value="F:/Jntuk/CustomAdapter" />
        <option value="F:/Jntuk/JntukInterview" />
        <option value="F:/Jntuk/NavigationDrawer1-master" />
        <option value="F:/Jntuk/SplashtoHomeAngga-master" />
        <option value="F:/Jntuk/NavigationDrawer" />
        <option value="F:/Jntuk/Interview-master" />
        <option value="F:/sem5/Android/Sem6" />
        <option value="F:/sem5/Android/ListActivity" />
        <option value="F:/Jntuk/Sliders-master" />
        <option value="F:/Jntuk/TickSeekBar-master" />
        <option value="F:/Android/android-ocr-master" />
        <option value="F:/Jntuk/IntroSlider" />
        <option value="F:/Android/MoviesAppFinal-master" />
        <option value="F:/Android/AndroidNewsApp" />
        <option value="F:/winter plan/android-news-app-master" />
        <option value="F:/winter plan/MoviesAppFinal-master" />
        <option value="F:/Android/example" />
        <option value="F:/Android/realm-recyclerview-master" />
        <option value="F:/Android/realm-recyclerview-master/example" />
        <option value="F:/sem5/Android/RelamRecyclerView" />
        <option value="F:/sem5/Android/Pavan" />
        <option value="F:/sem5/andr/practice" />
        <option value="F:/sem5/practice2" />
        <option value="F:/Android Stuff/BorrowBuddy" />
        <option value="F:/sem5/Android/Spinner" />
        <option value="F:/sem5/Android/SpinnerItem" />
        <option value="F:/sem5/Android/Spinner2" />
        <option value="F:/Android/Passinginfo" />
        <option value="F:/sem5/Android/Pract